TITLE: Zoomacode blog
TITLE_HTML: Zoomacode blog
TAGLINE: Блог про всякую техномагию магию, в основном расказы про мои эксперименты
#POSTS_PER_PAGE: 10
AUTHOR: Anton Golubtsov
#DISQUS: your-disqus-id
TIMEZONE: UTC
#POST_EXT: .rst
